galaxy_info:
  author: Javier Franco
  description: Instalador de Jboss EAP 
  company: Datasystems
  min_ansible_version: 2.9 
 
  platforms:
  - name: CentOS
    versions:
    - 7
    - 8 
  - name: RHEL 
    versions:
    - 7
    - 8 
 
  galaxy_tags:
    - web
    - system
    - application_server
