---
# tasks file for JBoss Firewall config
- name: Check firewall is up
  service:
    name: firewalld
    state: started 
  tags:
    - Check_firewall_is_up
    - firewall_config_yml

- name: Configure firewall
  firewalld:
    port: "{{ item.port }}"
    permanent: yes
    immediate: yes
    state: "{{ item.state }}"
  loop: "{{ jboss_firewall }}"
  tags:
    - firewall_config
    - firewall_config_yml
