---
# Configure the systemd service
- name: Create a default admin user for the web console
  shell: ./add-user.sh -u admin -p admin
  args:
    chdir: "{{ jboss_home }}/bin/"
  ignore_errors: yes
  tags:
    - web_console_user_create
    - install_yml

- name: Copy the init script to /etc/init.d/
  copy:
    src: "{{ jboss_home }}/bin/init.d/{{ jboss_service_script }}"
    dest: /etc/init.d/{{ service_name }}
    mode: 0755
    remote_src: yes
  tags:
    - copy_init_script
    - install_yml

- name: copy the JBoss service config to /etc/default/
  template:
    src: templates/{{ jboss_service_conf }}
    dest: /etc/default/
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
  notify: restart jboss
  tags:
    - copy_service_config
    - install_yml

- name: reload daemon
  systemd:
    daemon_reload: yes
  tags:
    - reload_daemon
    - install_yml

- name: configure jboss interfaces
  xml:
    path: "{{ jboss_home }}/{{ jboss_mode }}/configuration/{{ jboss_host_config }}"
    xpath: "{{ item.xpath }}"
    attribute: value
    value: "{{ item.value }}"
    namespaces:
      x: "{{ xml_namespace }}"
      attribute: value
      value: "{{ item.value }}"
  loop:
    - { xpath: "/x:{{ xml_root }}/x:interfaces/x:interface[@name='management']/x:inet-address", value: "${jboss.bind.address.management:{{ ansible_facts.default_ipv4.address}} }"}
    - { xpath: "/x:{{ xml_root }}/x:interfaces/x:interface[@name='public']/x:inet-address", value: "${jboss.bind.address:{{ ansible_facts.default_ipv4.address }} }"}
    - { xpath: "/x:{{ xml_root }}/x:interfaces/x:interface[@name='private']/x:inet-address", value: "${jboss.bind.address:{{ ansible_facts.default_ipv4.address }} }"}
  notify: restart jboss
  tags:
    - configure_jboss_interfaces
    - install_yml

- name: configure jboss domain controller authentication
  xml:
    path: "{{ jboss_home }}/{{ jboss_mode }}/configuration/{{ jboss_host_config }}"
    xpath: "{{ item.xpath }}"
    attribute: username
    value: "{{ item.value }}"
    namespaces:
      x: "{{ xml_namespace }}"
  loop:
    - { xpath: "/x:{{ xml_root }}/x:domain-controller/x:remote", value: "slave" }
  when: jboss_mode == 'domain'
  notify: restart jboss
  tags:
    - configure_jboss_domain_controller_authentication
    - install_yml

- name: configure the slave to point to the JBoss master
  xml:
    path: "{{ jboss_home }}/{{ jboss_mode }}/configuration/{{ jboss_host_config }}"
    xpath: "{{ item.xpath }}"
    attribute: host
    value: "{{ item.value }}"
    namespaces:
      x: "{{ xml_namespace }}"
  loop:
    - { xpath: "/x:{{ xml_root }}/x:domain-controller/x:remote/x:discovery-options/x:static-discovery", value: "${jboss.domain.master.address:{{ jboss_master }}}" }
  when: jboss_mode == 'domain'
  notify: restart jboss
  tags:
    - configure_the_slave_to_point_to_the_jboss_master
    - install_yml

- name: configure the secrets
  xml:
    path: "{{ jboss_home }}/{{ jboss_mode }}/configuration/{{ jboss_host_config }}"
    xpath: "{{ item.xpath }}"
    attribute: value
    value: "{{ item.value }}"
    namespaces:
      x: "{{ xml_namespace }}"
  loop:
    - { xpath: "/x:{{ xml_root }}/x:management/x:security-realms/x:security-realm/x:server-identities/x:secret", value: "c2xhdmU=" }
  when: jboss_mode == 'domain'
  notify: restart jboss
  tags:
    - configure_the_secrets
    - install_yml

- name: Remove default servers configs for the xml
  xml:
    path: "{{ jboss_home }}/{{ jboss_mode }}/configuration/{{ jboss_host_config }}"
    xpath: "{{ item.xpath }}"
    state: absent
    namespaces:
      x: "{{ xml_namespace }}"
  loop:
    - { xpath: "/x:{{ xml_root }}/x:servers/*", value: "${jboss.domain.master.address:{{ jboss_master }}}" }
  when: jboss_mode == 'domain'
  tags:
    - Remove_default_servers_configs_for_the_xml
    - install_yml

- name: enable to run on system boot
  shell: chkconfig {{ service_name }} on
  ignore_errors: yes
  changed_when: False
  tags:
    - enable_to_run_on_system_boot
    - install_yml

- name: Start the JBoss EAP service
  service:
    name: "{{ service_name }}"
    state: started
