---
# tasks file for jboss
- name: Create modules directory structure
  file:
    path: "{{ jboss_home }}{{ item.location }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
  loop: "{{ jboss_jdbc_module }}"
  tags:
    - create_module_structure
    - jdbc_driver_config_yml

- name: copy the driver config xml config
  template:
    src: templates/{{ item.file }}
    dest: "{{ jboss_home }}/{{ item.location }}{{ item.name }}"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: '0644'
  notify: restart jboss
  loop: "{{ jboss_jdbc_module }}"
  tags:
    - copy_jdbc_driver_config
    - jdbc_driver_config_yml

- name: copy the driver jar file
  get_url:
    url: "{{ repo_url }}{{ item.name }}"
    dest: "{{ jboss_home }}/{{ item.location }}"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
  loop: "{{ jboss_jdbc_drivers }}"
